// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1voa_Icwmsx5BfHyRWhwoYfTkCBP8ltY',
    appId: '1:901557265714:web:381de54366282091e2e32b',
    messagingSenderId: '901557265714',
    projectId: 'elpanzon-49f2d',
    authDomain: 'elpanzon-49f2d.firebaseapp.com',
    storageBucket: 'elpanzon-49f2d.firebasestorage.app',
    measurementId: 'G-5P6GFYJ622',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAODxcr1jgNw8mk_7yeTKHrHaBpZotyduw',
    appId: '1:901557265714:android:6f135610b422d924e2e32b',
    messagingSenderId: '901557265714',
    projectId: 'elpanzon-49f2d',
    storageBucket: 'elpanzon-49f2d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjQQsM7h998q9ysY8QAcDWIvkow-7isCQ',
    appId: '1:901557265714:ios:d5626c04384c69e2e2e32b',
    messagingSenderId: '901557265714',
    projectId: 'elpanzon-49f2d',
    storageBucket: 'elpanzon-49f2d.firebasestorage.app',
    iosBundleId: 'dro.panzon.tacoShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjQQsM7h998q9ysY8QAcDWIvkow-7isCQ',
    appId: '1:901557265714:ios:a1ec996fd972597ee2e32b',
    messagingSenderId: '901557265714',
    projectId: 'elpanzon-49f2d',
    storageBucket: 'elpanzon-49f2d.firebasestorage.app',
    iosBundleId: 'dro.panzon.elPanzon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1voa_Icwmsx5BfHyRWhwoYfTkCBP8ltY',
    appId: '1:901557265714:web:51e47c2a6d1bf98fe2e32b',
    messagingSenderId: '901557265714',
    projectId: 'elpanzon-49f2d',
    authDomain: 'elpanzon-49f2d.firebaseapp.com',
    storageBucket: 'elpanzon-49f2d.firebasestorage.app',
    measurementId: 'G-ZXGH4K40L3',
  );
}
